version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/match-server
    overwrite: yes

permissions:
  - object: /home/ubuntu/match-server
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root
